name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils_plus:
    git: https://github.com/seragsabrysakr/esc_pos_utils_plus.git
  flutter:
    sdk: flutter

  flutter_pos_printer_platform_image_3: ^1.1.2
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
